insert into state_master values (1, 'Andhra Pradesh');
insert into state_master values (2, 'Arunachal Pradesh');
insert into state_master values (3, 'Assam');
insert into state_master values (4, 'Bihar');
insert into state_master values (5, 'Chhattisgarh');
insert into state_master values (6, 'Goa');
insert into state_master values (7, 'Gujarat');
insert into state_master values (8, 'Haryana');
insert into state_master values (9, 'Himachal Pradesh');
insert into state_master values (10, 'Jammu and Kashmir');
insert into state_master values (11, 'Jharkhand');
insert into state_master values (12, 'Karnataka');
insert into state_master values (13, 'Kerala');
insert into state_master values (14, 'Madhya Pradesh');
insert into state_master values (15, 'Maharashtra');
insert into state_master values (16, 'Manipur');
insert into state_master values (17, 'Meghalaya');
insert into state_master values (18, 'Mizoram');
insert into state_master values (19, 'Nagaland');
insert into state_master values (20, 'Odisha');
insert into state_master values (21, 'Punjab');
insert into state_master values (22, 'Rajasthan');
insert into state_master values (23, 'Sikkim');
insert into state_master values (24, 'Tamil Nadu');
insert into state_master values (25, 'Telangana ');
insert into state_master values (26, 'Tripura');
insert into state_master values (27, 'Uttar Pradesh');
insert into state_master values (28, 'Uttarakhand');
insert into state_master values (29, 'West Bengal');