//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_FirstEntity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Login
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression("\\w{6,50}")]
        public string Username { get; set; }
        [Required]
        [RegularExpression("\\w{8,50}")]
        public string Password { get; set; }
    }
}
